name: car_rental_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  firebase_storage: ^12.3.0
  firebase_ui_auth: ^1.15.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  mocktail: ^1.0.4
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  uuid: ^4.5.0
  very_good_analysis: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  firebase_storage_mocks: ^0.7.0
  fake_cloud_firestore: ^3.0.2
  firebase_auth_mocks: ^0.14.1
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
