// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcm_pCFw4uC6Y_2cw6d7DI_eU08RWzAWc',
    appId: '1:541350283571:android:d7e039b65f1648267bd646',
    messagingSenderId: '541350283571',
    projectId: 'car-rental-app-8253b',
    databaseURL: 'https://car-rental-app-8253b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'car-rental-app-8253b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvDNJD-rpm5hZiKNbWkgpnbhvcEqu-kCw',
    appId: '1:541350283571:ios:aced5d382dfce39a7bd646',
    messagingSenderId: '541350283571',
    projectId: 'car-rental-app-8253b',
    databaseURL: 'https://car-rental-app-8253b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'car-rental-app-8253b.appspot.com',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLpctf10-F4I8ILGGsE7vLThFp2H0BEmM',
    appId: '1:541350283571:web:eb6b94c80f2a66c97bd646',
    messagingSenderId: '541350283571',
    projectId: 'car-rental-app-8253b',
    authDomain: 'car-rental-app-8253b.firebaseapp.com',
    databaseURL: 'https://car-rental-app-8253b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'car-rental-app-8253b.appspot.com',
  );

}